export { default as SvgError } from './assets/error.svg'
export { default as SvgGithub } from './assets/github.svg'
export { default as SvgHomeDescTitle } from './assets/home-desc-title.svg'
export { default as SvgLoading } from './assets/loading.svg'
export { default as SvgSubmit } from './assets/submit.svg'
export { default as SvgSuccess } from './assets/success.svg'
